### ISSUE TITLE
Invisible/phantom symbols after reopening the diagram.

### ISSUE THREAD

**Issue by RaghavendraP** [cloudskew/cloudskew#98] opened 2020-06-14 09:21 UTC
**Describe the bug**
After the diagram is closed and re-opened, few of the images in the diagram are not visible. But if I select the image location, it clearly shows there is an image but just not visible. So, if I try to change the image properties or do a double-click on the image, it becomes visible again. 

**To Reproduce**
Not guaranteed to reproduce consistently but mostly the images that are copy pasted from existing image in the same diagram is mostly missing. If instead of doing copy/paste operation, take a new image from the icons the images are fine.

**Desktop (please complete the following information):**
 - Browser chrome
 - OS: windows10

**Comment by mithunshanbhag** [comment] 2020-06-14 11:20
Hi @RaghavendraP,

Thanks for reporting this issue. I've encountered this issue once myself, but did not have a consistent/deterministic repro or enough details to file a bug. 

If you don't mind, could you please share the diagram (click on `share diagram` -> `create link (view only)`. I can then take a look. 

Probable root cause is colliding CSS class names in the icon SVGs. 

For now, you can workaround the issue in one of the following ways:
1. Select the invisible/phantom symbol, lock it (from the right-side properties bar) and then immediately unlock it.
2. Select the invisible/phantom symbol, press up arrow and then down arrow.

Looking forward to hearing back from you.

**Comment by RaghavendraP** [comment] 2020-06-14 15:32
Sadly, I tried to reproduce the issue in new diagram several times but couldn't reproduce. The initial diagram where I encountered the issue, I have deleted the copy pasted images and got the new ones from icon set. So, even there now I am not able to reproduce it. 
I can look for it and update here in future if I am able to reproduce myself in any diagram.

**Comment by mithunshanbhag** [comment] 2020-06-15 07:18
@RaghavendraP: No worries, I'll keep this issue open for tracking purposes. Please feel free to share repro'es or any diagnostic information here anytime.

**Comment by abenleaven** [comment] 2020-07-16 04:59
Hey there,

Same issues , double clicking usually brings it back into view

**Comment by mithunshanbhag** [comment] 2020-07-16 13:19
@abenleaven: If you don't mind, could you please share the diagram (click on share diagram -> create link (view only)? I'd like to take a look. Also please let me know if you're seeing any errors in the browser console (apart from some 404 errors which are expected).

**Comment by ckriutz** [comment] 2020-09-17 20:11
Adding to this as well. I expereince some of the same challenges. I have some symbols that upon a reload/refresh, they are invisable. They return as soon as I hover back over them, but until that happens, they don't render. It's the same icons/text, and not random.

**Comment by mithunshanbhag** [comment] 2020-09-18 07:31
@ckriutz: If you don't mind, could you please share the diagram (click on share diagram -> create link (view only)? I'd like to take a look. Also please let me know if you're seeing any errors in the browser console (apart from some 404 errors which are expected).

**Comment by mithunshanbhag** [comment] 2020-09-23 08:03
It looks like a z-index ordering issue.

Can you check if changing the z-index (as shown below) resolves the issue? In the meanwhile, I'll try to create a permanent fix for this issue (please note: fix might be very complicated and may only work for newer diagrams).

![GIF 9-23-2020 1-32-56 PM](https://user-images.githubusercontent.com/2327905/93984385-5bcdd700-fda1-11ea-91a4-ebbb0c6edef2.gif)

**Comment by ckriutz** [comment] 2020-09-23 17:44
I tried this today on both an older complicated diagram, as well as a newer simpler one I created today, and in both cases it did not resolve the issue.

**Comment by Nicolas-br** [comment] 2020-10-29 13:37
Got the same issue, hovering hover seems to bring those icons back. Not sure if it is related or not but the app keeps crashing (page becomes completely irresponsive). It is not usable.

**Comment by mithunshanbhag** [comment] 2020-10-29 14:01
@Nicolas-br: Can you please [export the diagram as JSON](https://github.com/cloudskew/cloudskew/releases/tag/v0.1.35-preview) and share it (privately if need be)?

**Comment by mithunshanbhag** [comment] 2020-10-29 22:13
Random notes & observations (while diagnosing this issue):

1. Auto-save not triggered when z-index of symbol changes.

**Comment by mithunshanbhag** [comment] 2020-11-05 11:16
Update: Turns out the bug is in a 3rd party component that CloudSkew uses. A fix will be made available to CloudSkew by Nov 24th. CloudSkew will then integrate the fix, test it out and will release it by Nov 27th.

**Comment by mithunshanbhag** [comment] 2020-11-18 09:38
**Good news**: A fix has now been issued and released to production. Going forward, new diagrams will not encounter this bug.

**Bad news**: Unfortunately, existing diagrams encountering this issue cannot be automatically patched/fixed. However a manual workaround is available:

1. [Export the diagram as a JSON file](https://github.com/cloudskew/cloudskew/releases/tag/v0.1.35-preview).
2. Some symbols might accidentally have the same z-index. If so, modify the z-indices so that they are unique.
3. [Create a new diagram by importing this modified JSON file](https://github.com/cloudskew/cloudskew/releases/tag/v0.1.36-preview).

You can also email us the diagram JSON (support@cloudskew.com) and we'll patch it for you.

**Closed by mithunshanbhag** 2020-11-18 09:38 UTC
Labels: bug, needs-more-details
