### ISSUE TITLE
Multi-line text boxes don't honor sizing after logging out and in again

### ISSUE THREAD

**Issue by sdavis3** [cloudskew/cloudskew#80] opened 2020-05-28 13:22 UTC
**Describe the bug**
When reloading a previously saved diagram, the text in a text box isn't being restored to its last state. The box seems to restore, but not the text inside. Seems to be isolated to multi-line text boxes, but I haven't confirmed that.

**To Reproduce**
1. Add a multiline text box with text content.
2. Exit cloudskew.
3. Login to cloudskew.
4. Diagram did not preserve text content as it was previously saved.

**Expected behavior**
Expect diagram to maintain the exact state when last saved.

**Screenshots**
See attached screenshots as examples below.

<img width="361" alt="Screen Shot 2020-05-28 at 9 17 37 AM" src="https://user-images.githubusercontent.com/1821509/83146633-9c079c00-a0c4-11ea-9b1e-75213e668ece.png">
<img width="936" alt="Screen Shot 2020-05-28 at 9 18 03 AM" src="https://user-images.githubusercontent.com/1821509/83146646-a1fd7d00-a0c4-11ea-9dd9-eb9777a0f820.png">

**Errors in browser console**
N/A

**Desktop (please complete the following information):**
 - Browser Chrome, Chromium Edge
 - OS: Windows 10, Mac

**Additional details**
N/A

**Comment by mithunshanbhag** [comment] 2020-05-28 18:18
Hi @sdavis3: Thanks for filing this issue. Yes, I'm able to reproduce this issue at my end. 
Will update here as soon as I find out the root cause.

**Comment by mithunshanbhag** [comment] 2020-06-03 11:53
[update: 6/3/2020] 

**Observations & findings:**

1. Issue can be reproduced even without logging out and logging back in. User can simply close the browser tab, open a new one and navigate to app.cloudskew.com and the issue will re-occur.

2. Issue will not reoccur if user simply refreshes the page.

3. Issue is caused during rendering (smoothing) of custom fonts: `Roboto Mono` in this case.

4. Consequently the fix involves falling back to the default font. 

**The good news:**

1. I currently have a fix in the works (still testing it). 

**The bad news:** 

1. Fix will not retroactively patch existing diagrams. It will however ensure that newer diagrams don't face this issue.

2. For existing diagrams, users will have to delete affected text boxes and re-add them. Unfortunately, this many mean a bit of work for the diagram author depending on the complexity of the diagram. :disappointed:


![GIF 6-3-2020 4-55-26 PM](https://user-images.githubusercontent.com/2327905/83632545-19e40f80-a5bd-11ea-82eb-b450eacd8e88.gif)

**Comment by mithunshanbhag** [comment] 2020-06-03 13:39
Fix has now been pushed to production. 

Closing this issue now. Please feel free to reactivate in case you're still experiencing issues.

**Closed by mithunshanbhag** 2020-06-03 13:39 UTC
Labels: bug

**Comment by mithunshanbhag** [comment] 2020-06-04 09:17
[update 6/4/2020] The root cause of this issue was [FOUC](https://en.wikipedia.org/wiki/Flash_of_unstyled_content). We're now using typekit's webfontloader to load the fonts synchronously. Fix is now in production.
