### ISSUE TITLE
Updating symbol's text annotation accidentally updated the symbol's svg content

### ISSUE THREAD

**Issue by futuredesignUK** [cloudskew/cloudskew#138] opened 2020-12-09 17:03 UTC
**Describe the bug**
After saving diagram as template canvas is blanked and diagram seems to be lost

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Save diagram as template
2. After save the canvas seemed to move down and shrink everything, almost like it had zoomed out and shifted the canvas
3. When exported diagram as PNG it saved with a huge surrounding canvas
4. Now reopening the diagram or template everything is blank

**Expected behavior**

Save diagram as template with blanking canvas

**Screenshots**
If possible, add screenshots and/or screen recordings which capture the issue. These greatly help investigations.

![image](https://user-images.githubusercontent.com/19208973/101661549-5008bd00-3a40-11eb-99b3-6ac09a16afca.png)

![image](https://user-images.githubusercontent.com/19208973/101661738-8d6d4a80-3a40-11eb-8c7e-c75c42fa4bf9.png)

**Errors in browser console**
If you observe any errors in the browser console, please paste those here.

**Desktop (please complete the following information):**
 - Browser Chrome
 - OS: MacOSX Big Sur

**Additional details**
Add any other details about the problem here.

redacted: link-to-diagram

Seems to have lost weeks of work as no version control on diagrams

It may be its moved the diagram far off the canvas so it cannot be viewed anymore

**Comment by mithunshanbhag** [comment] 2020-12-09 21:42
Hi @futuredesignUK, 

I'm investigating this right now and will post an update here as soon as I have a fix for this issue. My sincere apologies for this experience.

**Comment by mithunshanbhag** [comment] 2020-12-09 23:04
Update:  The good news is that the diagram contents have been recovered (please find json file emailed to you). You can create a new diagram by importing this json file [using the steps shown here](https://github.com/cloudskew/cloudskew/releases/tag/v0.1.36-preview) (please note that a new diagram will be created and original diagram will be left untouched).

I'm still investigating the root cause that led to the error and will update this github issue with any findings. But in the meanwhile, I hope the recovered json file unblocks you. Please let me know if you encounter any issue while importing the attached json file.

PS: I didn't want to attach/link the json file in this public github (since it may contain sensitive details) so am emailing you instead. Hope that is ok.

**Comment by futuredesignUK** [comment] 2020-12-09 23:28
@mithunshanbhag thanks for the speedy reply , I confirm the restore has worked and everything is back.

It's an excellent tool and this is the only bug I have noticed. 

The icon packs are really good and great to know can export as JSON for backups.

**Comment by mithunshanbhag** [comment] 2020-12-09 23:40
@futuredesignUK; Thanks for confirming that the recovered json file worked! Once again, my apologies for this issue. Hope to have the root cause identified very soon.

PS: Will leave this issue open for tracking the root cause.

**Closed** 2022-07-13 11:13 UTC
Labels: bug
