### ISSUE TITLE
Include possibility to create new/additional anchor points for icons

### ISSUE THREAD

**Issue by TarekSalha** [cloudskew/cloudskew#128] opened 2020-10-08 08:45 UTC
It would be great, if one could include additional anchor points for connectors to be able to customize the look of diagrams. I am especially thinking about connectors running through the text description of an icon, which is sometimes disturbing. Using this feature, it would be possible to end the connector before the text already.
![image](https://user-images.githubusercontent.com/25264670/95435823-5b157300-0953-11eb-8ed5-1fc4991ec93e.png)

**Comment by mithunshanbhag** [comment] 2020-10-12 04:33
Good suggestion. Will look at possible solutions.

PS: In the meanwhile, it is definitely possible to move the text annotations to prevent them from being overlapped by connectors (please see gif below).

![GIF](https://user-images.githubusercontent.com/2327905/95705582-24e93380-0c72-11eb-8d7d-37b97877b69f.gif)

**Comment by TarekSalha** [comment] 2020-10-12 07:43
totally true... That is a good workaround

**Comment by mithunshanbhag** [comment] 2020-10-31 10:41
Dupe of #97: [need more (or custom) connection points on symbols](https://github.com/cloudskew/cloudskew/issues/97)

**Closed by mithunshanbhag** 2020-10-31 10:41 UTC
Labels: feature-request
