### ISSUE TITLE
Roll back whatever you did today, Oct 2nd!

### ISSUE THREAD

**Issue by schord001** [cloudskew/cloudskew#127] opened 2020-10-02 17:54 UTC
**Describe the bug**
Crazy erratic behaviour when dragging icons across the canvas, dragging shapes or shape boundaries. Even the smallest movement of the mouse will send the icon flying off the screen or move the shape boundary either way short, or way long of where you want it. Also when dragging a shape boundary to move it/resize it, it doesn't take sometimes and ends up duplicating the edge of the shape, you then have to click to remove the duplicate edge to where it was originally.

**To Reproduce**
1. Go to canvas
2. Click on & drag icons or shapes

**Expected behavior**
See above. Icon or shape edge flys off to a random location

**Desktop (please complete the following information):**
 - Browser Chrome & Edge
 - OS: Windows 10

**Comment by mithunshanbhag** [comment] 2020-10-03 03:24
Hi @schord001, there haven't been any recent changes to the cloudskew editor ([see release notes](https://github.com/cloudskew/cloudskew/releases)). I'm unable to reproduce this issue on my end. Would it be possible for you to screen record the issue?

**Comment by mithunshanbhag** [comment] 2020-10-22 07:12
Hi @schord001, please let me know if the issue still exists for you. Else would it be ok to close this issue (given that I've been unable to reproduce this at my end and also no other customers have encountered this)?

**Closed** 2020-10-29 21:50 UTC
Labels: bug, no-repro

**Comment by mithunshanbhag** [comment] 2020-12-23 00:33
Likely dupe of #140

**Comment by mithunshanbhag** [comment] 2021-12-06 07:32
**Update**: I've just pushed a fix to resolve the following user-reported issues: 
* fast mouse movements while dragging/resizing/moving shapes
* diagram freezes

Affected diagrams should auto-heal on page load (and even if your issue isn't resolved, the telemetry data will move us closer to a diagnosis).

**Note**: To load the latest/non-cached version of the app, go to http://app.cloudskew.com and press:
* CTRL + SHIFT + R (on windows/linux)
* CMD + SHIFT + R (on mac)
