### ISSUE TITLE
collaborative design

### ISSUE THREAD

**Issue by AllieUbisse** [cloudskew/cloudskew#122] opened 2020-09-08 16:37 UTC
**Is your feature request related to a problem? Please describe.**
sharing with edit rights, I'm working remotely with my colleague and we can he can not edit<br>
![image](https://user-images.githubusercontent.com/67786379/92503474-99f3c400-f201-11ea-9b23-4c651de915a0.png)

**Describe the solution you'd like**
Please add the can *Create Link(Edit mode)*

**Comment by mithunshanbhag** [comment] 2020-11-14 22:38
Dupe of #60.

**Closed by mithunshanbhag** 2020-11-14 22:38 UTC
Labels: feature-request
