### ISSUE TITLE
right click menu context gone when Hover to nested menu.

### ISSUE THREAD

**Issue by ryanhs** [cloudskew/cloudskew#79] opened 2020-05-28 12:05 UTC
**Describe the bug**

right click menu context gone when Hover to nested menu.

**To Reproduce**
1. right click on shape
2. go to grouping / order.
3. mouse to nested menu

**Expected behavior**
menu still exists there, and be able to click on nested menu

**Screenshots**

![download (4)](https://user-images.githubusercontent.com/7413776/83138913-ba49b800-a115-11ea-8519-c84d821c9726.png)

**Errors in browser console**

```javascript
main-es2015.e1102da775f0242825e1.js:1 ERROR TypeError: Cannot read property 'focus' of null
    at end (main-es2015.e1102da775f0242825e1.js:1)
    at e.toggleAnimation (main-es2015.e1102da775f0242825e1.js:1)
    at ww.<anonymous> (main-es2015.e1102da775f0242825e1.js:1)
    at ww.notify (main-es2015.e1102da775f0242825e1.js:1)
    at e.trigger (main-es2015.e1102da775f0242825e1.js:1)
    at e.triggerBeforeOpen (main-es2015.e1102da775f0242825e1.js:1)
    at e.openMenu (main-es2015.e1102da775f0242825e1.js:1)
    at e.afterCloseMenu (main-es2015.e1102da775f0242825e1.js:1)
    at ww.<anonymous> (main-es2015.e1102da775f0242825e1.js:1)
    at ww.notify (main-es2015.e1102da775f0242825e1.js:1)
```

**Desktop (please complete the following information):**
 - Browser Chromium
 - OS Ubuntu 20

**Comment by mithunshanbhag** [comment] 2020-05-28 12:35
This might be a dupe of #61.

**Comment by mithunshanbhag** [comment] 2020-06-02 07:33
Fix pushed to production. Please reactivate if you see this issue re-occurring.

![GIF 6-2-2020 1-01-01 PM](https://user-images.githubusercontent.com/2327905/83492776-66522100-a4d1-11ea-8310-a125735161fb.gif)

**Closed by mithunshanbhag** 2020-06-02 07:33 UTC
Labels: bug

**Comment by ryanhs** [comment] 2020-06-02 07:40
@mithunshanbhag Thank you very much!
