### ISSUE TITLE
Tooltips are not shown after clicking on Home icon

### ISSUE THREAD

**Issue by SathyaBhat** [cloudskew/cloudskew#36] opened 2020-01-18 17:14 UTC
**Describe the bug**
The tooltips are not shown after clicking on the Home icon

**To Reproduce**
1. Load cloudskew
2. Hover on buttons, see that the tooltips are shown
3. Click on the Home icon
4. Upon hover, tooltips are not shown

**Expected behaviour**
Tooltips are shown

screencapture:

![2020-01-18_17-18-29](https://user-images.githubusercontent.com/25424/72668287-ee0d2680-3a2d-11ea-9619-3ebd1c34c730.gif)

**Errors in browser console**
No errors

**Desktop (please complete the following information):**
 - Chrome Version 79.0.3945.117 (Official Build) (64-bit)
 - OS: Windows 10

**Additional details**
Add any other details about the problem here.

**Comment by mithunshanbhag** [comment] 2020-01-18 20:43
Thanks @SathyaBhat. Screen capture was very helpful. 

I'm now able to reproduce the issue at my end. Taking a look at why this is happening.....

**Comment by mithunshanbhag** [comment] 2020-02-04 17:45
Updates:
1. I've fixed the issue of the tooltip not get loaded after route reactivates (when home icon is clicked). 
2. I've also removed the link from the home icon since it is redundant (it reactivates the same route). 

Fix is already deployed. Closing this issue.

**Closed by mithunshanbhag** 2020-02-04 17:45 UTC
Labels: bug
