### ISSUE TITLE
Dragging Near Canvas Edge

### ISSUE THREAD

**Issue by michaelbudney-dc** [cloudskew/cloudskew#140] opened 2020-12-22 00:00 UTC
**Describe the bug**
When an object is dragged near the edge of the canvas it suddenly vanishes.  It winds up so far away I get lost trying to find the objects on the original diagram.  Undo does not fix the problem.

**To Reproduce**
1. Add some items to the diagram.
2. Drag on of the items and let it get near the edge.

**Expected behavior**
The item to not disappear and have the canvas grow to infinite size.

**Screenshots**
There is an error related to drag drop in the console.
![image](https://user-images.githubusercontent.com/75453614/102833008-ec767c00-43bd-11eb-8961-f3bc83a75505.png)
[app.cloudskew.com-1608595052235.log](https://github.com/cloudskew/cloudskew/files/5727049/app.cloudskew.com-1608595052235.log)

**Desktop (please complete the following information):**
Windows 10 Desktop
Microsoft Edge
Version 87.0.664.66 (Official build) (64-bit)

**Additional details**
Add any other details about the problem here.

**Comment by mithunshanbhag** [comment] 2020-12-22 04:15
Hi @michaelbudney-dc, 

Unfortunately, I've been unable to reproduce this issue at my end. 

Would you mind sharing the following information?

1. What is your screen/monitor resolution?

2. Would you mind sharing a gif/video of the issue OR [exporting the diagram to JSON](https://github.com/cloudskew/cloudskew/releases/tag/v0.1.35-preview) and sharing it out?

If the diagram contains sensitive information and you'd rather not share it here publicly, please feel free to email it to us at support@cloudskew.com. Once again, apologies for the inconvenience.

**Comment by mithunshanbhag** [comment] 2020-12-23 00:34
#132 and #127 are likely dupes on this issue.

**Comment by michaelbudney-dc** [comment] 2020-12-23 14:20
> #132 and #127 are likely dupes on this issue.

I agree, they seem similar, especially #132.  At first I thought the drag was trying to snap to a new page.

**Comment by mgowing** [comment] 2020-12-23 20:43
I was the reporter of #132. Never got around to getting a video, but here it is.
https://user-images.githubusercontent.com/68403079/103035545-2ade7900-452d-11eb-8db4-b8679e2bc1f1.mp4

**Comment by mithunshanbhag** [comment] 2020-12-23 22:36
Hi @mgowing. Thanks for the video. Any chance you can send me the [exported diagram JSON](https://github.com/cloudskew/cloudskew/releases/tag/v0.1.35-preview) as well? You can paste a link here or mail it at support@cloudskew.com. Would love to take a look.

**Comment by mgowing** [comment] 2020-12-28 19:36
Unfortunately it stopped happening after I deleted the objects, and refreshed the page. I'll export one when it occurs again.

**Comment by mithunshanbhag** [comment] 2021-12-06 07:31
**Update**: I've just pushed a fix to resolve the following user-reported issues: 
* fast mouse movements while dragging
* diagram freezes

Affected diagrams should auto-heal on page load (and even if your issue isn't resolved, the telemetry data will move us closer to a diagnosis).

**Note**: To load the latest/non-cached version of the app, go to http://app.cloudskew.com and press:
* CTRL + SHIFT + R (on windows/linux)
* CMD + SHIFT + R (on mac)

**Closed** 2021-12-10 15:25 UTC
Labels: bug
