### ISSUE TITLE
Issue with resizing/moving shapes.

### ISSUE THREAD

**Issue by mgowing** [cloudskew/cloudskew#132] opened 2020-10-20 13:38 UTC
**Describe the bug**
I have a drawing or two that run into this issue when I am moving/resizing shapes. Instead of the shape following my mouse with the move or resize, it's like my mouse's DPI increases 10x and the shape goes super fast in that direction.

**To Reproduce**
Open Drawing.
Resize/move shape a few times.

**Expected behavior**
The shape move/resize should follow my mouse.

**Screenshots**
Schedule a meeting, if you want to see this.

**Errors in browser console**
N/A

**Desktop (please complete the following information):**
 - Browser Edge Chromium
 - OS: Win10

**Additional details**
N/A

**Comment by mithunshanbhag** [comment] 2020-10-20 17:27
Hi @mgowing: Thanks for reporting this issue. Would it be grab a screen recording? I've been unable to reproduce this issue at my end.

**Comment by TanGolf** [comment] 2020-10-23 09:57
Also seeing this. It was working fine on the 15th October and I logged back in and now when I move an object it disappears off into a distant location. Same with resizing.

**Comment by mithunshanbhag** [comment] 2020-10-23 13:23
Hi @TanGolf : Would it be possible to grab a screen recording? Also are you observing any errors in the browser console?

**Comment by mithunshanbhag** [comment] 2020-11-02 08:51
Closing this issue since I'm unable to repro it at my end. Please feel free to reactivate if this issue still persists for you.

**Comment by mithunshanbhag** [comment] 2020-12-23 00:32
Possibly related to #140.

**Closed by mithunshanbhag** 2020-12-23 00:32 UTC
Labels: bug, no-repro

**Comment by mithunshanbhag** [comment] 2021-12-06 07:31
**Update**: I've just pushed a fix to resolve the following user-reported issues: 
* fast mouse movements while dragging/resizing/moving shapes
* diagram freezes

Affected diagrams should auto-heal on page load (and even if your issue isn't resolved, the telemetry data will move us closer to a diagnosis).

**Note**: To load the latest/non-cached version of the app, go to http://app.cloudskew.com and press:
* CTRL + SHIFT + R (on windows/linux)
* CMD + SHIFT + R (on mac)
